config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "/my_listings", to: "pages#my_listings", as: "my_listings"
  get "/my_offers", to: "pages#my_offers", as: "my_offers"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # nested resources to allow user to create review to the listing

  resources :listings do
    resources :reviews, only: %i[new create index]
    resources :offers, only: [:create] # Allows creating a offer straight from listing
  end

  resources :reviews, only: %i[destroy]

  resources :offers, only: [:index, :show, :new, :update, :destroy] do
    member do
      put :accept_offer
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
class Listing < ApplicationRecord
  # geocoded_by :address # telling Geocoder to geocode address field
  # after_validation :geocode, if: :will_save_change_to_address? # telling Geocoder to geocode only when changes made to address
  # has_many :offers, dependent: :destroy
  # has_many :reviews, dependent: :destroy
  # belongs_to :user
  # validates :brand, presence: true
  # validates :description, presence: true
  # validates :price, presence: true
  # validates :address, presence: true
  # validates :transmission, presence: true
  # validates :category, presence: true
  # has_many_attached :photos



  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :offers, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user
  validates_presence_of :brand, :description, :price, :address, :transmission, :category, :name
  has_many_attached :photos


end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :listing
  belongs_to :user

  before_create :set_defaults

  private

  def set_defaults
    self.status = "PROPOSAL"
    # self.user_id = @currentuser.id
    # self.listing_id = @currentlisting.id (params[:id])
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :listing
  belongs_to :user

  validates :rating, numericality: { only_float: true, message: "should be a number!" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :listings
  has_many :offers, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # to make all pages unaccessable before login
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :email, :contact_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :email, :contact_number])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # whitelisting these pages to public, without log in [devise]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    # if params[:query1].present? && params[:query2].blank?
    #   @listings = Listing.where('brand ILIKE ?', params[:query1])
    # elsif params[:query1].blank? && params[:query2].present?
    #   @listings = Listing.where('price <= ?', params[:query2])
    # elsif params[:query1].present? && params[:query2].present?
    #   @listings = Listing.where('brand ILIKE ? AND price <= ?', params[:query1], params[:query2])
    # else
    #   @listings = Listing.all
    # end
    @listings = Listing.all
    @listings = @listings.where('brand ILIKE ?', params[:search_brand]) if params['search_brand'].present?
    @listings = @listings.where('price <= ?', params[:search_price]) if params['search_price'].present?
    @listings = @listings.where('category ILIKE ?', params[:search_category]) if params['search_category'].present?
    @listings = @listings.where('transmission ILIKE ?', params[:search_transmission]) if params['search_transmission'].present?

    # The `geocoded` scope filters only flats with coordinates
    @markers = @listings.geocoded.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude,
        info_window: render_to_string(partial: "popup_map", locals: {listing: listing})
      }
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @reviews = @listing.reviews
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)

    @listing.user_id = current_user.id # Hard coding. To update to user_id when devise is done.
    if @listing.save
      redirect_to my_listings_path, notice: "Listing was successfully created."
    else
      render :new
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])

    if @listing.update(listing_params)
      redirect_to listing_path(@listing), notice: "Listing was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    redirect_to my_listings_path, notice: "Listing was successfully deleted."
  end

  private

  def listing_params
    params.require(:listing).permit(:name, :brand, :transmission, :category, :description, :price, :address, photos: [])
  end

  def offer_params
    params.require(:offer).permit(:price, :start_date, :end_date)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = Offer.all
    # @user_offers = Offer.where(user_id: 1)
  end

  def new
    @offer = Offer.new
  end

  def show
    @offer = Offer.find(params[:id])
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @offer = Offer.new(price: params[:price], start_date: params[:start_date], end_date: params[:end_date])
    @offer.listing = @listing
    @offer.user = current_user

    if @offer.save
      redirect_to @listing, notice: "Offer sent successfully."
    else
      render 'new'
    end
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.status = "PROPOSAL"

    if @offer.update(offer_params)
      redirect_to offer_path, alert: "The counter-offer has been sent!"
    else
      render :edit
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    redirect_to listings_path, notice: "Offer was successfully deleted."
  end

  def accept_offer
    @offer = Offer.find(params[:id])
    @offer.status = "CONFIRMED"
    @offer.save
    redirect_to offer_path, alert: "You have accepted an offer. Status has changed from Proposal to Confirmed."
  end

  private

  def offer_params
    params.require(:offer).permit(:price, :start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # whitelisting home page
  skip_before_action :authenticate_user!, only: :home

  def home
    @listings = Listing.limit(6)
  end

  def my_listings
    @my_listings = current_user.listings
  end

  def my_offers
    @my_offers = current_user.offers
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_listing, only: %i[new create index]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.listing = @listing
    @review.user = current_user
    @listing.user == current_user ? @review.for_host = false : @review.for_host = true

    # to validate if review if valid
    if @review.save
      redirect_to listing_path(@listing)

    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @reviews = @listing.reviews
  end

  def destroy
    @review = Review.find(params[:id])
    listing = @review.listing
    @review.destroy
    redirect_to listing_path(listing)
  end

  private

  def set_listing
    @listing = Listing.find(params[:listing_id])
  end

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DriveShare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%# mapbox %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>

    <%= render "shared/footer" %>
</html>

app/views/listings/_popup_map.html.erb
<p><%= listing.name %></p>
<p>address: <%= listing.address %></p>
<p>$<%= listing.price %>/day</p>

app/views/listings/edit.html.erb
<div class="container" style="margin-left: 8px">
  <title>Edit Listing</title>
  <style>
    /* CSS code for the h1 element */
    h1 {
      font-size: 28px;
      font-weight: bold;
      margin-bottom: 20px;
    }

    /* CSS code for the label elements */
    label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }

    /* CSS code for the input elements */
    input[type="text"],
    input[type="file"],
    textarea {
      width: 100%;
      padding: 10px;
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
    }

    /* CSS code for the submit button */
    input[type="submit"] {
      background-color: #87CEEB;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
  </style>
    <h1>Edit Listing</h1>
   <%= form_for @listing do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :brand %>
    <%= f.select :brand, options_for_select([["Select One", ""], 'Tesla', 'Audi', 'BMW', 'Honda', 'Mazda', "Toyota", "Mercedes"])%><br>

    <%= f.label :category %>
    <%= f.select :category, options_for_select([["Select One", ""], 'SUV', 'Sedan', 'Van', 'Lorry', 'Truck'])%><br>

    <%= f.label :transmission %>
    <%= f.select :transmission, options_for_select([["Select One", ""], 'Manual', 'Auto'])%><br>

    <%= f.label :description %>
    <%= f.text_area :description %><br>

    <%= f.label :price, "Price Per Day" %>
    <%= f.text_field :price %><br>

    <%= f.label :address %>
    <%= f.text_field :address %><br>

    <div class="upload">
      <%= f.label :photos, "Upload Photos" %>
      <%= f.file_field :photos, multiple: true %>
    </div>

    <%= f.submit "Edit Listing" %>
  <% end %>
</div>

app/views/listings/index.html.erb
<div class="container" style="margin-top: 15px;">
  <h1>Listings</h1>
  <%= form_with url: listings_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :search_brand,
    params[:search_brand],
    class: "form-control",
    placeholder: "Search by Brand"
  %>
  <%= text_field_tag :search_price,
    params[:search_price],
    class: "form-control",
    placeholder: "Search by Price, less than"
  %>
  <%= text_field_tag :search_category,
    params[:search_category],
    class: "form-control",
    placeholder: "Search by Category"
  %>
  <%= text_field_tag :search_transmission,
    params[:search_transmission],
    class: "form-control",
    placeholder: "Search by Transmission"
  %>
  <%= submit_tag "Search", class: "my-button"%>
  <% end %>


  <div data-controller="map"
        id="map"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value="<%= @markers.to_json %>"
        style='width: 100%; height: 300px;'>
  </div>

  <%= link_to 'New Listing', new_listing_path, class: "btn btn-info mt-3 mb-3" %>

  <%# check app/views/shared/_listings_cards.html.erb to edit %>
  <%# make sure @listings = Lisitng.all is defined in controller %>
  <%= render "shared/listings_cards", listings: @listings %>
</div>

app/views/listings/new.html.erb
<div class="container" style="margin-left: 8px">

<title>Create Listing</title>
<style>
  /* CSS code for the h1 element */
  h1 {
    font-size: 28px;
    font-weight: bold;
    margin-bottom: 20px;
  }

  /* CSS code for the label elements */
  label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
  }

  /* CSS code for the input elements */
  input[type="text"],
  input[type="file"],
  textarea {
    width: 100%;
    padding: 10px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  /* CSS code for the submit button */
  input[type="submit"] {
    background-color: #4CAF50;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .upload {
    margin-bottom: 10px;
  }

  label[for="listing_name"]:after,
  label[for="listing_brand"]:after,
  label[for="listing_category"]:after,
  label[for="listing_transmission"]:after,
  label[for="listing_description"]:after,
  label[for="listing_price"]:after,
  label[for="listing_address"]:after {
    content: " *";
    color: red;
  }

</style>


  <h1>Create Listing</h1>
  <%= form_for @listing do |f| %>
    <%= f.label :name  %>
    <%= f.text_field :name %><br>

  <%= f.label :brand %>
  <%= f.select :brand, options_for_select([["Select One", ""], 'Tesla', 'Audi', 'BMW', 'Honda', 'Mazda']), required: true %><br>

  <%= f.label :category %>
  <%= f.select :category, options_for_select([["Select One", ""], 'SUV', 'Sedan', 'Van', 'Lorry', 'Truck']), required: true %><br>

  <%= f.label :transmission %>
  <%= f.select :transmission, options_for_select([["Select One", ""], 'Manual', 'Auto']), required: true %><br>

  <%= f.label :description %>
  <%= f.text_area :description, required: true %><br>

  <%= f.label :price %>
  <%= f.text_field :price, required: true %><br>

  <%= f.label :address %>
  <%= f.text_field :address, required: true %><br>

  <div class="upload">
    <%= f.label :photos, "Upload Photos" %>
    <%= f.file_field :photos, multiple: true, required: true %>
  </div>

  <%= f.submit "Create Listing" %>
<% end %>

</div>

app/views/listings/show.html.erb
<div class="container" style="margin-top: 16px">

  <% if @listing.photos.attached? %>
        <% @listing.photos.each do |photo| %>
        <%= image_tag photo, class: "card-img-top", style: "width: 250px; height:250px;" %>
        <% end %>
    <% end %>

  <h2><%= @listing.brand.to_s.capitalize %> <%= @listing.transmission.to_s.capitalize %></h2>
  <p><strong>Category:</strong> <%= @listing.category.to_s.capitalize %></p>
  <p><strong>Transmission:</strong> <%= @listing.transmission.to_s.capitalize %></p>
  <p><strong>Description:</strong> <%= @listing.description.capitalize %></p>
  <p><strong>Price:</strong> $<%= @listing.price %></p>
  <p><strong>Address:</strong> <%= @listing.address.capitalize %></p>
  <p><strong>User:</strong> <%= @listing.user.username %></p>


  <br>

  <% if @listing.user == current_user %>
    <%= link_to 'Edit', edit_listing_path(@listing) %> |
  <% else %>
  <% end %>
  <%= link_to 'Back', listings_path %>
  <br>
  <br>

  <%# below is to test function of creating a new review for listing %>

  <p></p>

  <% if @listing.user != current_user %>

    <p><strong> Make a booking now: </strong></p>

    <%= form_with(model: @offer, url: listing_offers_path(@listing), local: true) do |form| %>
      <div class="form-group">
        <%= form.label :price %>
        <%= form.text_field :price, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :start_date %>
        <%= form.date_field :start_date, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :end_date %>
        <%= form.date_field :end_date, class: "form-control" %>
      </div>
      <br>
      <%= form.submit "Send Offer", class: "btn btn-outline-primary" %>
    <% end %>
  <% else %>
    <p><i>- This is your listing -</i></p>
  <% end %>

  <br>
  <p><strong>Reviews</strong></p>
  <% if @reviews.count == 0 %>
    <%= "There are currently no reviews for this listing!" %>
  <% else %>
    <ul class="list-group">
      <% @reviews.each do |review| %>
        <li class="list-group-item">
        <%= review.rating %> <%= review.description %>
        <% if review.user == current_user %>
          <%= link_to "Delete", review_path(review),
          class: "btn btn-warning",
          style: "color: white;",
          data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete this review?"}
          %>
        <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <br>

  <% if @listing.user != current_user %>
    <%= link_to "Leave a Review", new_listing_review_path(@listing),
        class: "btn btn-primary",
        style: "color: white;"
    %>
  <% else %>
  <% end %>
</div>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/offers/create.html.erb
<h1>Offers#create</h1>
<p>Find me in app/views/offers/create.html.erb</p>

app/views/offers/destroy.html.erb
<h1>Offers#destroy</h1>
<p>Find me in app/views/offers/destroy.html.erb</p>

app/views/offers/index.html.erb
<div class="container">
  <h1>Your Current Offers</h1>

  <ul class="list-group">
    <% @offers.each do |offer| %>
      <li class="list-group-item">
        <strong>Offer ID:</strong> <%= offer.id %><br>
        <strong>Price Per Day:</strong> <%= offer.price %><br>
        <strong>Start Date:</strong> <%= offer.start_date %><br>
        <strong>End Date:</strong> <%= offer.end_date %><br>
        <strong>Status:</strong> <%= offer.status %><br>
        <strong>Car Listing ID:</strong> <%= offer.listing_id %><br>
        <strong>Renter ID: </strong> <%= offer.user_id %><br>
        <!-- This portion here is to get the Host info that is tagged to the listing -->
        <% listing_id = offer.listing_id %>
        <% listing = Listing.find(listing_id) %>
        <% host_id = listing.user_id %>
        <% host = User.find(host_id) %>
        <strong>Car Owner ID:</strong> <%= host.id %> /
        <strong>Name of Owner</strong> <%= host.first_name.capitalize %>
        <%= link_to "Details", offer_path(offer.id), class: "btn btn-primary" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/offers/new.html.erb
<div class="container">
  <h1> Create New Offer For Listing ID : X </h1>

    <%= form_with(model: @offer, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :price %>
        <%= form.text_field :price, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :start_date %>
        <%= form.date_field :start_date, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :end_date %>
        <%= form.date_field :end_date, class: "form-control" %>
      </div>
      <br>
      <%= form.submit "Send Offer", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/offers/show.html.erb
<div class="container" style="margin-top: 15px;">
  <h1>This is the specific offer page</h1>
  <p> Showing details for Offer ID: <%= "#{@offer.id}" %><br>

  <br>

  <strong>Price Per Day:</strong> <%= @offer.price %><br>
  <strong>Start Date:</strong> <%= @offer.start_date %><br>
  <strong>End Date:</strong> <%= @offer.end_date %><br>
  <strong>Current Status:</strong> <%= @offer.status %><br>
  <strong>Created by:</strong> <%= @offer.user_id %><br>
  <strong>Listing ID:</strong> <%= @offer.listing_id %><br>

  <% if @offer.status == "PROPOSAL" && current_user == @offer.listing.user %>
    <%= button_to "Accept Offer", accept_offer_offer_path(@offer), method: :put, class: "btn btn-success" %>
  <% else %>
  <% end %>

  <% if @offer.status == "PROPOSAL" && current_user == @offer.user %>
    <%= button_to "Delete Offer", offer_path(@offer), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-warning" %>
  <% else %>
  <% end %>
  <br>


  <!-- Bottom removed counter-offer for Demo, but 100% working>

  <%# <h2> Want to send a counter-offer? </h2> %>

  <%# <%= form_with(model: @offer, local: true) do |form| %>
    <%# <div class="form-group"> %>
      <%# <%= form.label :price %>
      <%# <%= form.text_field :price, class: "form-control" %>
    <%# </div> %>
    <%# <div class="form-group"> %>
      <%# <%= form.label :start_date %>
      <%# <%= form.date_field :start_date, class: "form-control" %>
    <%# </div> %>
    <%# <div class="form-group"> %>
      <%# <%= form.label :end_date %>
      <%# <%= form.date_field :end_date, class: "form-control" %>
    <%# </div> %>
    <%# <br> %>
    <%# <%= form.submit "Send Counter-offer", class: "btn btn-primary" %>
  <%# <% end %>
</div>

app/views/pages/my_listings.html.erb
<div class="container">
  <h1>My Listings</h1>
  <style>
    table {
      border-collapse: collapse;
      width: 90%;
    }

    th, td {
      text-align: left;
      padding: 8px;
    }

    th {
      background-color: #4CAF50;
      color: black;
    }

    tr:nth-child(even) {
      background-color: #f2f2f2;
    }

    tr:hover {
      background-color: #ddd;
    }

    .actions {
      display: flex;
      justify-content: space-between;
    }

    .button {
      background-color: #87CEEB;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }

    .card-img-top {
      object-fit: cover;
      height: 200px;
    }
  </style>

  <%= link_to 'New Listing', new_listing_path, class: "btn btn-info mt-3 mb-3" %>

  <%= render "shared/listings_cards", listings: @my_listings, edit_button: true, delete_button: true %>
</div>

app/views/reviews/index.html.erb
<p><strong>Reviews</strong></p>
<ul class="list-group">
  <% @reviews.each do |review| %>
    <li class="list-group-item">
    <%= review.rating %> <%= review.description %>
    <% if review.user == current_user %>
      <%= link_to "Delete", review_path(review),
      class: "btn btn-danger",
      data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete this task?"}
       %>
    <% end %>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<div class="container">
  <h1>New review</h1>

  Here are some details for your previous booking! Share some thoughts below! <br>

  <strong><%= @listing.brand.capitalize %> <%= @listing.transmission.capitalize %></strong>
  <strong>Category:</strong> <%= @listing.category.to_s.capitalize %><br>
  <strong>Transmission:</strong> <%= @listing.transmission.to_s.capitalize %><br>
  <strong>Description:</strong> <%= @listing.description.capitalize %><br>
  <strong>Price:</strong> $<%= @listing.price %><br>
  <strong>Address:</strong> <%= @listing.address.capitalize %><br>
  <strong>Your Host:</strong> <%= @listing.user.first_name %> <%= @listing.user.last_name %><br>
  <br>

  <%= simple_form_for [@listing, @review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :description %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>




<%# # !!!!! %>
<%# # need to have a 'show' (views/listings/show.html.erb)? to display all the reviews under the listing? %>
<%# # refering to lecture 'advanced routing' 'Create view' section %>

app/views/shared/_listings_cards.html.erb
  <div class="row">
    <%# declare locals variable when using partial %>
    <%# render "shared/listings_cards", listings: @my_listings, show_edit_button: true %>
    <% local_assigns[:listings].each do |listing| %>
      <div class="col-md-4">
        <div class="card mb-4 card-trip">
          <div class="img-container">
            <div class="listing-image">
              <% if listing.photos.attached? %>
                <% listing.photos.each do |photo| %>
                  <%= image_tag photo, class: "card-img-top" %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="card-body">
            <h5 class="card-title"><strong><%= listing.name.upcase %></strong></h5>
            <div class="listing-details">
              <div class="address"><%= listing.address.upcase %></div>
              <div class="price"><span>S$<%= listing.price %></span> /day</div>
            </div>
            <div class="actions">
              <%= link_to 'Show', listing_path(listing), class: "my-button" %>

              <%# declare locals when using partial to show button %>
              <%# render "shared/listings_cards", listings: @my_listings, show_edit_button: true %>
              <% if local_assigns[:edit_button] %>
                <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-primary" %>
              <% end %>

              <% if local_assigns[:delete_button] %>
                <%= link_to 'Delete', listing_path(listing),
                data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete this task?"},
                class: 'btn btn-primary' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "drivesharelogo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "avatar_photo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Offers", my_offers_path, class: "dropdown-item" %>
              <%= link_to "My Listings", my_listings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>